spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 128Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
          env:
          - name: ACTIVEMQ_SERVICE_NAME
            value: broker-amq-tcp
          - name: ACTIVEMQ_USERNAME
            value: connect
          - name: ACTIVEMQ_PASSWORD
            value: admin
          - name: MYSQL_SERVICE_NAME
            value: mysql-55-rhel7
          - name: MYSQL_SERVICE_DATABASE
            value: bank_data
          - name: MYSQL_SERVICE_USERNAME
            value: connect
          - name: MYSQL_SERVICE_PASSWORD
            value: admin